jobs:

  borrow_problematic_scenarios:

    name: 'Borrow: Problematic Scenarios'

    description: |
      Run Borrow problematic scenarios under MRI

    priority: 0

    run_when:
      branch name matches master or borrow:
        type: branch
        include_match: '^.*(master|borrow).*$'
        exclude_match: '^.*(no-ci|hotspot).*$'

    context:

      include:
        - cider-ci/shared/main_context.yml
        - cider-ci/tasks/borrow_problematic_scenarios.yml

      task_defaults:
        traits:
          g2016: true
        load: 2
        max_trials: 6
        include:
          - cider-ci/task_components/database.yml
