jobs:

  borrow_broken_scenarios:

    name: 'Borrow: Broken Scenarios'

    description: |
      Run Borrow flapping scenarios

    priority: 0

    run_when:
      branch name matches master or borrow:
        type: branch
        include_match: '^.*(master|borrow).*$'
        exclude_match: '^.*(no-ci|hotspot).*$'

    context:

      task_defaults:
        load: 1.5
        max_trials: 2
        eager_trials: 1
        include:
          - cider-ci/task_components/database.yml

      include:
        - cider-ci/shared/main_context.yml
        - cider-ci/tasks/borrow_broken_scenarios.yml
