jobs:

  manage_flapping_scenarios:

    name: 'Manage: Flapping Scenarios'

    description: |
      Run Manage flapping scenarios

    priority: -1

    run_when:
      branch name matches master or manage:
        type: branch
        include_match: '^.*(master|manage).*$'
        exclude_match: '^.*(no-ci|hotspot).*$'

    context:

      task_defaults:
        traits:
          g2016: true
        load: 2.0
        max_trials: 20
        eager_trials: 20
        include:
          - cider-ci/task_components/database.yml

      include:
        - cider-ci/shared/main_context.yml
        - cider-ci/tasks/manage_flapping_scenarios.yml
