jobs:

  manage_scenarios:

    name: 'Manage: Scenarios'

    description: |
      Run Manage scenarios under MRI

    priority: 0

    run_when:
      branch name matches master or manage:
        type: branch
        include_match: '^.*(master|manage|v4_pg_tests).*$'
        exclude_match: '^.*(no-ci|hotspot).*$'

    context:

      task_defaults:
        traits:
          g2016: true
        load: 1.5
        max_trials: 2
        include:
          - cider-ci/task_components/database.yml

      include:
        - cider-ci/shared/main_context.yml
        - cider-ci/tasks/manage_scenarios.yml
