jobs:

  procurement_flapping_scenarios:

    name: 'Procurement: Flapping Scenarios'

    description: |
      Run procurement flapping scenarios

    priority: 0

    run_when:
      branch name matches master or procurement:
        type: branch
        include_match: '^.*(master|procurement).*$'
        exclude_match: '^.*(no-ci|hotspot).*$'

    context:

      task_defaults:
        traits:
          g2016: true
        load: 1.5
        max_trials: 4
        eager_trials: 1
        include:
          - cider-ci/task_components/database.yml

      include:
        - cider-ci/shared/main_context.yml
        - cider-ci/tasks/procurement_flapping_scenarios.yml
